function [BW] = createMask()
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder app. The colorspace and
%  range for each channel of the colorspace were set within the app. The
%  segmentation mask is returned in BW, and a composite of the mask and
%  original RGB images is returned in maskedRGBImage.

% Auto-generated by colorThresholder app on 17-Nov-2017
%------------------------------------------------------


%Convert RGB image to chosen color space
cam = webcam('USB Video Device');
cam.resolution = '1280x960';
Preview = figure;
%figure(Preview,"Preview");
preview(cam);
pause();
I = snapshot(cam);
Image = figure;
imshow(I);

% Define thresholds for channel 1 based on histogram settings
channel1Min = 91.000;
channel1Max = 255.000;

% Define thresholds for channel 2 based on histogram settings
channel2Min = 84.000;
channel2Max = 255.000;

% Define thresholds for channel 3 based on histogram settings
channel3Min = 86.000;
channel3Max = 255.000;

% Create mask based on chosen histogram thresholds
sliderBW = (I(:,:,1) >= channel1Min ) & (I(:,:,1) <= channel1Max) & ...
    (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
    (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);
BW = sliderBW;
BitMask = figure;
spy(BW);
end
