function H = getH(r,b,a,xt,yt,zt)

H = [cos(a)*cos(b), cos(a)*sin(b)*sin(r)-sin(a)*cos(r),cos(a)*sin(b)*cos(r)+sin(a)*sin(r), xt; ...
   sin(a)*cos(b), sin(a)*sin(b)*sin(r)+cos(a)*cos(r), sin(a)*sin(b)*cos(r)-cos(a)*sin(r), yt; ...
   -sin(b), cos(b)*sin(r), cos(b)*cos(r), zt; ...
   0,0,0,1];
end

